-- ═══════════════════════════════════════════════════════════════════
-- SackGlobal — schema inicial (portfolio + social + reacciones)
-- Aplica esto en un proyecto Supabase vacio (SQL Editor)
-- ═══════════════════════════════════════════════════════════════════

-- 1) users — espejo de auth.users con nickname / avatar publicos
create table if not exists public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  email text,
  name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

create policy users_public_read on public.users
  for select using (true);

create policy users_self_insert on public.users
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy users_self_update on public.users
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- 2) repo_interactions — reacciones + comentarios sobre repos de GitHub
create table if not exists public.repo_interactions (
  id uuid primary key default gen_random_uuid(),
  repo_id bigint not null,
  repo_name text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('reaction','comment')),
  emoji text,
  content text,
  created_at timestamptz not null default now(),
  check (
    (type = 'reaction' and emoji is not null and content is null) or
    (type = 'comment' and content is not null and emoji is null)
  )
);

create index idx_repo_interactions_repo_id on public.repo_interactions(repo_id);
create index idx_repo_interactions_user_id on public.repo_interactions(user_id);
create index idx_repo_interactions_type on public.repo_interactions(type);

create unique index uq_repo_interactions_reaction
  on public.repo_interactions(repo_id, user_id, emoji)
  where type = 'reaction';

alter table public.repo_interactions enable row level security;

create policy repo_interactions_read on public.repo_interactions
  for select using (true);

create policy repo_interactions_auth_insert on public.repo_interactions
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy repo_interactions_own_delete on public.repo_interactions
  for delete to authenticated
  using (auth.uid() = user_id);

-- 3) posts — timeline publico, escritura por owner
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  content text not null,
  image_url text,
  created_at timestamptz not null default now()
);
create index idx_posts_created_at on public.posts(created_at desc);
create index idx_posts_user_id on public.posts(user_id);

alter table public.posts enable row level security;

create policy posts_read on public.posts for select using (true);

create policy posts_owner_insert on public.posts
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy posts_owner_update on public.posts
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy posts_owner_delete on public.posts
  for delete to authenticated
  using (auth.uid() = user_id);

-- 4) news — solo admin publica
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  notice text not null,
  image_url text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_news_created_at on public.news(created_at desc);

alter table public.news enable row level security;

create policy news_read on public.news for select using (true);

create policy news_admin_insert on public.news
  for insert to authenticated
  with check ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com');

create policy news_admin_update on public.news
  for update to authenticated
  using ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com');

create policy news_admin_delete on public.news
  for delete to authenticated
  using ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com');

-- 5) social_links — solo admin edita
create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  channel_name text,
  iconify_name text,
  created_at timestamptz not null default now()
);

alter table public.social_links enable row level security;

create policy social_links_read on public.social_links
  for select using (true);

create policy social_links_admin_all on public.social_links
  for all to authenticated
  using ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com');

-- 6) Trigger: al crearse/actualizarse un auth.users, sincroniza public.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (user_id, nickname, email, name, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'user_name',
      new.raw_user_meta_data->>'nickname',
      new.raw_user_meta_data->>'preferred_username',
      new.email
    ),
    new.email,
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name'),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (user_id) do update set
    nickname = excluded.nickname,
    email = excluded.email,
    name = excluded.name,
    avatar_url = excluded.avatar_url;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update on auth.users
  for each row execute function public.handle_new_user();
