-- ═══════════════════════════════════════════════════════════════════
-- Migración SackGlobal — schema para portfolio + social + reacciones
-- ═══════════════════════════════════════════════════════════════════

-- Limpia tablas de la era blogdelsack que ya no usamos
drop table if exists public.twitch_commands cascade;
drop table if exists public."suggestedGame" cascade;
drop table if exists public.user_permissions cascade;

-- Migrar `post` -> `posts` con columna `content`
do $$
begin
  if to_regclass('public.post') is not null and to_regclass('public.posts') is null then
    execute 'alter table public.post rename to posts';
    if exists (select 1 from information_schema.columns
               where table_schema='public' and table_name='posts' and column_name='post') then
      execute 'alter table public.posts rename column post to content';
    end if;
  end if;
end $$;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  content text not null,
  image_url text,
  created_at timestamptz not null default now()
);
create index if not exists idx_posts_created_at on public.posts(created_at desc);
create index if not exists idx_posts_user_id on public.posts(user_id);

alter table public.posts enable row level security;
drop policy if exists posts_read on public.posts;
create policy posts_read on public.posts for select using (true);
drop policy if exists posts_owner_insert on public.posts;
create policy posts_owner_insert on public.posts for insert to authenticated
  with check (auth.uid() = user_id);
drop policy if exists posts_owner_update on public.posts;
create policy posts_owner_update on public.posts for update to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists posts_owner_delete on public.posts;
create policy posts_owner_delete on public.posts for delete to authenticated
  using (auth.uid() = user_id);

-- News (ya existía; garantizamos columnas y policies)
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  notice text not null,
  image_url text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

do $$
begin
  if exists (select 1 from information_schema.columns
             where table_schema='public' and table_name='news' and column_name='news_id') then
    execute 'alter table public.news rename column news_id to id';
  end if;
end $$;

create index if not exists idx_news_created_at on public.news(created_at desc);
alter table public.news enable row level security;
drop policy if exists news_read on public.news;
create policy news_read on public.news for select using (true);
drop policy if exists news_admin_write on public.news;
create policy news_admin_write on public.news for insert to authenticated
  with check (
    (auth.jwt() ->> 'email') = 'johanjafet4@gmail.com'
  );
drop policy if exists news_admin_delete on public.news;
create policy news_admin_delete on public.news for delete to authenticated
  using (
    (auth.jwt() ->> 'email') = 'johanjafet4@gmail.com'
  );

-- Migrar social_media -> social_links con columnas snake_case
do $$
begin
  if to_regclass('public.social_media') is not null and to_regclass('public.social_links') is null then
    execute 'alter table public.social_media rename to social_links';
    if exists (select 1 from information_schema.columns
               where table_schema='public' and table_name='social_links' and column_name='socialMediaName') then
      execute 'alter table public.social_links rename column "socialMediaName" to name';
    end if;
    if exists (select 1 from information_schema.columns
               where table_schema='public' and table_name='social_links' and column_name='Link') then
      execute 'alter table public.social_links rename column "Link" to url';
    end if;
    if exists (select 1 from information_schema.columns
               where table_schema='public' and table_name='social_links' and column_name='channelName') then
      execute 'alter table public.social_links rename column "channelName" to channel_name';
    end if;
    if exists (select 1 from information_schema.columns
               where table_schema='public' and table_name='social_links' and column_name='iconifyName') then
      execute 'alter table public.social_links rename column "iconifyName" to iconify_name';
    end if;
  end if;
end $$;

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  channel_name text,
  iconify_name text,
  created_at timestamptz not null default now()
);

alter table public.social_links enable row level security;
drop policy if exists social_links_read on public.social_links;
create policy social_links_read on public.social_links for select using (true);
drop policy if exists social_links_admin_write on public.social_links;
create policy social_links_admin_write on public.social_links for all to authenticated
  using ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'johanjafet4@gmail.com');
